// 온톨로지 확장(커버리지 폭) — 일반 건기식 성분 + 흔한 질환/기능 동의어. §13.1 폭 = 데이터.
// 평가셋(독립 듀얼라벨)과 무관하게 일반 지식으로 작성(held-out 채점). 본체 ontology.ts가 spread.
import type { OntologyEntry } from './ontology'

export const ONTOLOGY_EXT: OntologyEntry[] = [
  // ── 흔한 증상(condition) — "열나는데 약"·"두통에 ○○" 류에 판단이 뜨도록. 안전한 변형만(과매칭 회피) ──
  { canonical: '발열', variants: ['발열', '열나', '열이 나', '열이나', '고열', '미열', '몸에 열', '열이 올라'], type: 'disease' },
  { canonical: '두통', variants: ['두통', '머리 아프', '머리 아픈', '머리 아파', '머리가 아프', '머리가 아픈', '머리가 아파', '머리 통증', '머리가 지끈'], type: 'disease' },
  { canonical: '몸살', variants: ['몸살', '몸살기', '온몸이 쑤', '몸이 쑤'], type: 'disease' },
  { canonical: '인후통', variants: ['인후통', '목 아프', '목 아픈', '목 아파', '목이 아프', '목이 아픈', '목이 아파', '목감기', '목 통증', '목이 따끔', '목이 칼칼', '목이 부었'], type: 'disease' },
  { canonical: '치통', variants: ['치통', '이가 아프', '이가 아픈', '이가 아파', '잇몸 아프', '잇몸 아픈'], type: 'disease' },
  { canonical: '복통', variants: ['복통', '배 아프', '배 아픈', '배 아파', '배가 아프', '배가 아픈', '배가 아파', '아랫배 아프'], type: 'disease' },
  { canonical: '자폐스펙트럼장애', variants: ['자폐', '자폐증', '자폐 스펙트럼', '자폐스펙트럼', 'autism', '아스퍼거'], type: 'disease', tags: ['chronic_irreversible'] },
  // ── 질환 대량 확장 (expand-disease-ontology 워크플로 147종, 생성+적대검증) — §13.1 폭 ──
  { canonical: "심방세동", variants: ["심방세동", "심방 세동", "atrial fibrillation", "afib", "심방잔떨림"], type: "disease", tags: ["chronic_irreversible"] },
  { canonical: "심장판막증", variants: ["심장판막증", "판막질환", "판막질환증", "승모판협착", "승모판막", "대동맥판막", "판막역류", "심장판막", "valvular"], type: "disease", tags: ["chronic_irreversible"] },
  { canonical: "말초동맥질환", variants: ["말초동맥질환", "말초혈관질환", "말초동맥", "버거씨병", "버거병", "하지동맥", "다리혈관 막힘", "peripheral artery"], type: "disease", tags: ["chronic_irreversible"] },
  { canonical: "심부정맥혈전증", variants: ["심부정맥혈전증", "심부정맥 혈전", "다리혈전", "하지정맥 혈전", "deep vein thrombosis", "dvt"], type: "disease" },
  { canonical: "폐색전증", variants: ["폐색전증", "폐동맥색전", "폐혈전색전", "pulmonary embolism", "폐혈전"], type: "disease" },
  { canonical: "뇌동맥류", variants: ["뇌동맥류", "뇌혈관 꽈리", "미파열동맥류", "cerebral aneurysm", "뇌혈관류"], type: "disease" },
  { canonical: "일과성허혈발작", variants: ["일과성허혈발작", "일과성 허혈", "미니뇌졸중", "작은뇌졸중", "transient ischemic", "tia"], type: "disease" },
  { canonical: "대동맥류", variants: ["대동맥류", "복부대동맥류", "흉부대동맥류", "대동맥박리", "대동맥 박리", "aortic aneurysm", "대동맥 꽈리"], type: "disease" },
  { canonical: "레이노증후군", variants: ["레이노증후군", "레이노 증후군", "레이노병", "수족냉증", "손발 차가움", "raynaud"], type: "disease", tags: ["chronic_irreversible"] },
  { canonical: "림프부종", variants: ["림프부종", "림프 부종", "팔다리 붓기", "lymphedema", "림프순환"], type: "disease", tags: ["chronic_irreversible"] },
  { canonical: "심내막염", variants: ["심내막염", "감염성 심내막염", "심장내막염", "endocarditis"], type: "disease", tags: ["infectious"] },
  { canonical: "심근염", variants: ["심근염", "바이러스성 심근염", "myocarditis"], type: "disease", tags: ["infectious"] },
  { canonical: "기립성빈맥증후군", variants: ["기립성빈맥증후군", "기립성빈맥", "체위성빈맥", "기립성 빈맥", "pots", "기립 빈맥"], type: "disease" },
  { canonical: "선천성심장병", variants: ["선천성심장병", "선천성 심장병", "선천성심질환", "심방중격결손", "심실중격결손", "팔로4징", "청색증 심장", "congenital heart"], type: "disease", tags: ["chronic_irreversible"] },
  { canonical: "위궤양", variants: ["위궤양", "위 궤양", "gastric ulcer", "소화성궤양", "소화성 궤양", "peptic ulcer"], type: "disease" },
  { canonical: "십이지장궤양", variants: ["십이지장궤양", "십이지장 궤양", "duodenal ulcer"], type: "disease" },
  { canonical: "과민성대장증후군", variants: ["과민성대장증후군", "과민성 대장 증후군", "과민성장증후군", "과민성 장 증후군", "과민성대장", "과민성 대장", "ibs", "irritable bowel"], type: "disease" },
  { canonical: "크론병", variants: ["크론병", "크론 병", "크론씨병", "crohn"], type: "disease", tags: ["chronic_irreversible"] },
  { canonical: "궤양성대장염", variants: ["궤양성대장염", "궤양성 대장염", "ulcerative colitis", "염증성장질환", "염증성 장질환", "염증성 장 질환"], type: "disease", tags: ["chronic_irreversible"] },
  { canonical: "지방간", variants: ["지방간", "지방 간", "fatty liver", "비알코올성 지방간", "알코올성 지방간", "지방간염"], type: "disease" },
  { canonical: "간경변", variants: ["간경변", "간경화", "간 경변", "간 경화", "cirrhosis", "liver cirrhosis"], type: "disease", tags: ["chronic_irreversible"] },
  { canonical: "췌장염", variants: ["췌장염", "췌장 염", "이자염", "pancreatitis", "급성췌장염", "만성췌장염"], type: "disease" },
  { canonical: "담낭염", variants: ["담낭염", "담낭 염", "쓸개염", "cholecystitis", "담도염", "담관염"], type: "disease" },
  { canonical: "치핵", variants: ["치핵", "치핵증", "hemorrhoid", "내치핵", "외치핵"], type: "disease" },
  { canonical: "설사", variants: ["설사", "묽은 변", "물똥", "diarrhea", "급성 설사", "만성 설사"], type: "disease" },
  { canonical: "소화불량", variants: ["소화불량", "소화 불량", "체기", "더부룩", "명치통증", "명치 통증", "dyspepsia", "기능성 소화불량"], type: "disease" },
  { canonical: "장폐색", variants: ["장폐색", "장 폐색", "장막힘", "장 막힘", "장폐쇄", "ileus", "bowel obstruction"], type: "disease" },
  { canonical: "게실염", variants: ["게실염", "게실 염", "대장게실", "대장 게실", "diverticulitis", "게실증"], type: "disease" },
  { canonical: "쿠싱증후군", variants: ["쿠싱증후군", "쿠싱 증후군", "cushing"], type: "disease" },
  { canonical: "부신기능저하증", variants: ["부신기능저하증", "부신기능저하", "부신기능 저하", "에디슨병", "에디슨 병", "addison", "부신피질기능저하"], type: "disease", tags: ["chronic_irreversible"] },
  { canonical: "요붕증", variants: ["요붕증", "요붕", "diabetes insipidus"], type: "disease" },
  { canonical: "당뇨병성신증", variants: ["당뇨병성 신증", "당뇨병성신증", "당뇨병성 콩팥병", "당뇨병성 신장병", "diabetic nephropathy"], type: "disease", tags: ["chronic_irreversible"] },
  { canonical: "사구체신염", variants: ["사구체신염", "사구체 신염", "신장염", "glomerulonephritis"], type: "disease" },
  { canonical: "신증후군", variants: ["신증후군", "콩팥증후군", "nephrotic syndrome", "단백뇨 증후군"], type: "disease" },
  { canonical: "다낭신", variants: ["다낭성 신장", "다낭신", "다낭성 콩팥", "polycystic kidney", "다낭성신증"], type: "disease", tags: ["chronic_irreversible"] },
  { canonical: "신우신염", variants: ["신우신염", "신우 신염", "콩팥 감염", "pyelonephritis"], type: "disease", tags: ["infectious"] },
  { canonical: "전립선염", variants: ["전립선염", "전립샘염", "prostatitis"], type: "disease" },
  { canonical: "혈뇨", variants: ["혈뇨", "소변에 피", "소변 피", "피오줌", "오줌에 피"], type: "disease" },
  { canonical: "단백뇨", variants: ["단백뇨", "소변 거품", "거품뇨", "proteinuria"], type: "disease" },
  { canonical: "과민성방광", variants: ["과민성 방광", "과민성방광", "빈뇨", "절박뇨", "야간뇨", "overactive bladder"], type: "disease" },
  { canonical: "발기부전", variants: ["발기부전", "발기 부전", "성기능장애", "성기능 장애", "음위", "erectile dysfunction"], type: "disease" },
  { canonical: "다낭난소증후군", variants: ["다낭난소증후군", "다낭성 난소", "다낭난소", "다낭성난소증후군", "다낭성 난소 증후군", "pcos"], type: "disease" },
  { canonical: "류마티스관절염", variants: ["류마티스관절염", "류마티스 관절염", "류마티스성 관절염", "류마티즘", "류머티즘", "류마티스", "rheumatoid arthritis", "자가면역 관절염"], type: "disease", tags: ["chronic_irreversible"] },
  { canonical: "골관절염", variants: ["골관절염", "골 관절염", "퇴행성관절염", "퇴행성 관절염", "퇴행성 무릎관절", "무릎 퇴행성", "osteoarthritis", "닳은 연골", "연골 닳"], type: "disease", tags: ["chronic_irreversible"] },
  { canonical: "허리디스크", variants: ["허리디스크", "허리 디스크", "추간판탈출", "추간판탈출증", "추간판 탈출", "요추간판탈출", "요추 디스크", "디스크 탈출", "herniated disc", "허리 통증 디스크", "좌골신경통"], type: "disease" },
  { canonical: "목디스크", variants: ["목디스크", "목 디스크", "경추디스크", "경추 디스크", "경추간판탈출", "경추간판탈출증", "목 추간판"], type: "disease" },
  { canonical: "척추관협착증", variants: ["척추관협착증", "척추관 협착증", "척추관협착", "척추 협착", "요추관협착증", "요추관 협착증", "spinal stenosis"], type: "disease", tags: ["chronic_irreversible"] },
  { canonical: "오십견", variants: ["오십견", "동결견", "유착성 관절낭염", "유착성관절낭염", "어깨 굳음", "frozen shoulder", "어깨 결림증"], type: "disease" },
  { canonical: "회전근개파열", variants: ["회전근개파열", "회전근개 파열", "회전근개", "어깨 힘줄 파열", "rotator cuff", "극상근 파열"], type: "disease" },
  { canonical: "근감소증", variants: ["근감소증", "근육감소증", "근육 감소", "근손실", "근육 손실", "사코페니아", "sarcopenia", "노인 근육감소"], type: "disease", tags: ["chronic_irreversible"] },
  { canonical: "테니스엘보", variants: ["테니스엘보", "테니스 엘보", "외측상과염", "외측 상과염", "팔꿈치 바깥쪽 통증", "tennis elbow"], type: "disease" },
  { canonical: "골프엘보", variants: ["골프엘보", "골프 엘보", "내측상과염", "내측 상과염", "팔꿈치 안쪽 통증", "golfer elbow"], type: "disease" },
  { canonical: "족저근막염", variants: ["족저근막염", "족저 근막염", "발바닥 통증", "발바닥 근막", "발뒤꿈치 통증", "발꿈치 통증", "plantar fasciitis"], type: "disease" },
  { canonical: "손목터널증후군", variants: ["손목터널증후군", "손목 터널 증후군", "수근관증후군", "수근관 증후군", "손목 저림", "carpal tunnel"], type: "disease" },
  { canonical: "거북목증후군", variants: ["거북목증후군", "거북목 증후군", "거북목", "일자목", "일자 목", "텍스트넥", "text neck", "전방머리자세"], type: "disease" },
  { canonical: "척추측만증", variants: ["척추측만증", "척추 측만증", "측만증", "척추 휨", "휜 척추", "scoliosis"], type: "disease" },
  { canonical: "고관절질환", variants: ["고관절질환", "고관절 질환", "고관절염", "고관절 통증", "대퇴골두 괴사", "대퇴골두무혈성괴사", "엉덩이 관절 통증"], type: "disease" },
  { canonical: "섬유근육통", variants: ["섬유근육통", "섬유근통", "섬유 근육통", "fibromyalgia", "전신 근육통증"], type: "disease", tags: ["chronic_irreversible"] },
  { canonical: "파킨슨병", variants: ["파킨슨병", "파킨슨", "파킨슨씨병", "파킨슨 증후군", "parkinson", "손떨림 병", "수전증 병"], type: "disease", tags: ["chronic_irreversible"] },
  { canonical: "뇌전증", variants: ["뇌전증", "간질", "경련 발작", "발작 질환", "epilepsy", "지랄병"], type: "disease" },
  { canonical: "공황장애", variants: ["공황장애", "공황 장애", "공황발작", "공황 발작", "panic disorder", "패닉장애"], type: "disease" },
  { canonical: "불안장애", variants: ["불안장애", "범불안장애", "사회불안", "사회공포증", "anxiety disorder", "신경증"], type: "disease" },
  { canonical: "조현병", variants: ["조현병", "정신분열", "정신분열증", "schizophrenia", "환청 환각 병"], type: "disease", tags: ["chronic_irreversible"] },
  { canonical: "ADHD", variants: ["ADHD", "adhd", "주의력결핍", "주의력 결핍", "과잉행동장애", "주의력결핍 과잉행동", "산만증"], type: "disease" },
  { canonical: "수면무호흡증", variants: ["수면무호흡증", "수면무호흡", "수면 무호흡", "코골이 무호흡", "폐쇄성수면무호흡", "sleep apnea", "자다가 숨 멈"], type: "disease" },
  { canonical: "이명", variants: ["이명", "귀울림", "귀 울림", "귀에서 소리", "tinnitus", "귀울음"], type: "disease" },
  { canonical: "어지럼증", variants: ["어지럼증", "어지럼", "어지러움", "현기증", "현훈", "vertigo", "전정신경"], type: "disease" },
  { canonical: "긴장성두통", variants: ["긴장성두통", "긴장형두통", "긴장성 두통", "스트레스성 두통", "tension headache", "뒷목 당기는 두통"], type: "disease" },
  { canonical: "양극성장애", variants: ["양극성장애", "양극성 장애", "조울증", "조울병", "bipolar", "기분조절 장애"], type: "disease", tags: ["chronic_irreversible"] },
  { canonical: "강박장애", variants: ["강박장애", "강박증", "강박 신경증", "ocd", "확인 강박", "결벽 강박"], type: "disease" },
  { canonical: "외상후스트레스장애", variants: ["외상후스트레스장애", "외상 후 스트레스", "트라우마 장애", "ptsd", "심리적 외상"], type: "disease" },
  { canonical: "말초신경병증", variants: ["말초신경병증", "말초신경병", "손발 저림 병", "다발신경병증", "신경병성통증", "당뇨병성 신경병증", "neuropathy"], type: "disease" },
  { canonical: "안면마비", variants: ["안면마비", "안면 마비", "구안와사", "벨마비", "벨 마비", "facial palsy", "얼굴 마비"], type: "disease" },
  { canonical: "다발성경화증", variants: ["다발성경화증", "다발경화증", "multiple sclerosis"], type: "disease", tags: ["chronic_irreversible"] },
  { canonical: "이석증", variants: ["이석증", "양성돌발성체위현훈", "양성 자세 현훈", "BPPV", "귀돌"], type: "disease" },
  { canonical: "메니에르병", variants: ["메니에르병", "메니에르", "메니에르증후군", "Meniere", "Ménière"], type: "disease", tags: ["chronic_irreversible"] },
  { canonical: "난청", variants: ["난청", "청력저하", "청력 저하", "귀가 안 들", "잘 안 들려", "노인성난청", "돌발성난청", "hearing loss"], type: "disease" },
  { canonical: "후각장애", variants: ["후각장애", "후각 장애", "냄새를 못", "냄새가 안", "후각 상실", "후각 소실", "anosmia"], type: "disease" },
  { canonical: "코피", variants: ["코피", "비출혈", "코피가", "코에서 피", "nosebleed", "epistaxis"], type: "disease" },
  { canonical: "쉰목소리", variants: ["쉰목소리", "쉰 목소리", "목소리가 쉬", "음성변화", "애성", "목쉼", "성대결절", "성대 결절"], type: "disease" },
  { canonical: "후두암", variants: ["후두암", "후두 암", "성대암", "laryngeal cancer"], type: "disease", tags: ["cancer"] },
  { canonical: "구강암", variants: ["구강암", "입안 암", "혀암", "설암", "구강 암", "oral cancer"], type: "disease", tags: ["cancer"] },
  { canonical: "비인두암", variants: ["비인두암", "상인두암", "코인두암", "비인두 암", "nasopharyngeal"], type: "disease", tags: ["cancer"] },
  { canonical: "인후두역류", variants: ["인후두역류", "인후두 역류", "후두인두역류", "목까지 역류", "LPR", "목이물감"], type: "disease" },
  { canonical: "기관지확장증", variants: ["기관지확장증", "기관지 확장증", "bronchiectasis"], type: "disease", tags: ["chronic_irreversible"] },
  { canonical: "폐섬유증", variants: ["폐섬유증", "특발성폐섬유증", "폐 섬유증", "간질성폐질환", "간질성 폐질환", "pulmonary fibrosis"], type: "disease", tags: ["chronic_irreversible"] },
  { canonical: "에이즈", variants: ["에이즈", "후천성면역결핍증", "후천성 면역결핍", "에이치아이브이", "hiv", "aids"], type: "disease", tags: ["chronic_irreversible", "infectious"] },
  { canonical: "요로감염", variants: ["요로감염", "요로 감염", "요로감염증", "요도염", "urinary tract infection"], type: "disease", tags: ["infectious"] },
  { canonical: "봉와직염", variants: ["봉와직염", "봉소염", "연조직염", "cellulitis"], type: "disease", tags: ["infectious"] },
  { canonical: "헬리코박터감염", variants: ["헬리코박터감염", "헬리코박터", "헬리코박터 파일로리", "헬리코박터균", "helicobacter", "위염균", "위장균 감염"], type: "disease", tags: ["infectious"] },
  { canonical: "옴", variants: ["옴", "옴벌레", "옴진드기", "개선충", "scabies"], type: "disease", tags: ["infectious"] },
  { canonical: "세균성이질", variants: ["세균성이질", "세균성 이질", "이질균", "시겔라", "shigella", "dysentery"], type: "disease", tags: ["infectious"] },
  { canonical: "콜레라", variants: ["콜레라", "cholera", "콜레라균"], type: "disease", tags: ["infectious"] },
  { canonical: "일본뇌염", variants: ["일본뇌염", "japanese encephalitis", "뇌염모기", "일본 뇌염"], type: "disease", tags: ["infectious"] },
  { canonical: "풍진", variants: ["풍진", "rubella", "독일홍역", "삼일홍역"], type: "disease", tags: ["infectious"] },
  { canonical: "파상풍", variants: ["파상풍", "tetanus", "破傷風"], type: "disease", tags: ["infectious"] },
  { canonical: "사람유두종바이러스감염", variants: ["사람유두종바이러스감염", "사람유두종바이러스", "인유두종바이러스", "에이치피브이", "hpv", "자궁경부암백신", "곤지름", "곤지름 사마귀"], type: "disease", tags: ["infectious"] },
  { canonical: "성기헤르페스", variants: ["성기헤르페스", "음부포진", "단순포진", "herpes"], type: "disease", tags: ["chronic_irreversible", "infectious"] },
  { canonical: "매독", variants: ["매독", "syphilis", "성병 매독"], type: "disease", tags: ["infectious"] },
  { canonical: "임질", variants: ["임질", "임균", "gonorrhea"], type: "disease", tags: ["infectious"] },
  { canonical: "패혈증", variants: ["패혈증", "sepsis", "혈액감염", "균혈증"], type: "disease", tags: ["infectious"] },
  { canonical: "농가진", variants: ["농가진", "impetigo", "고름딱지"], type: "disease", tags: ["infectious"] },
  { canonical: "위암", variants: ["위암", "stomach cancer", "gastric cancer", "위 선암", "위선암"], type: "disease", tags: ["cancer"] },
  { canonical: "대장암", variants: ["대장암", "직장암", "결장암", "대장 직장암", "colorectal cancer", "colon cancer", "결직장암"], type: "disease", tags: ["cancer"] },
  { canonical: "간암", variants: ["간암", "간세포암", "간세포암종", "liver cancer", "원발성 간암"], type: "disease", tags: ["cancer"] },
  { canonical: "유방암", variants: ["유방암", "유방 종양", "breast cancer", "유방 악성종양", "유선암"], type: "disease", tags: ["cancer"] },
  { canonical: "자궁경부암", variants: ["자궁경부암", "자궁 경부암", "자궁암", "cervical cancer", "경부암", "hpv 자궁암"], type: "disease", tags: ["cancer"] },
  { canonical: "갑상선암", variants: ["갑상선암", "갑상샘암", "갑상선 종양", "갑상선 결절암", "thyroid cancer", "갑상선유두암"], type: "disease", tags: ["cancer"] },
  { canonical: "전립선암", variants: ["전립선암", "전립샘암", "prostate cancer", "전립선 종양", "전립선 악성종양"], type: "disease", tags: ["cancer"] },
  { canonical: "췌장암", variants: ["췌장암", "이자암", "췌장 종양", "pancreatic cancer", "췌장 악성종양"], type: "disease", tags: ["cancer"] },
  { canonical: "백혈병", variants: ["백혈병", "혈액암", "급성백혈병", "만성백혈병", "leukemia", "급성골수성백혈병", "급성림프구성백혈병"], type: "disease", tags: ["cancer"] },
  { canonical: "림프종", variants: ["림프종", "악성림프종", "림프암", "림프절암", "lymphoma", "호지킨림프종", "비호지킨림프종"], type: "disease", tags: ["cancer"] },
  { canonical: "위장관기질종양", variants: ["위장관기질종양", "위장관 기질종양", "gist", "지스트 종양"], type: "disease", tags: ["cancer"] },
  { canonical: "식도암", variants: ["식도암", "esophageal cancer", "식도 종양", "식도 악성종양"], type: "disease", tags: ["cancer"] },
  { canonical: "난소암", variants: ["난소암", "ovarian cancer", "난소 종양", "난소 악성종양"], type: "disease", tags: ["cancer"] },
  { canonical: "신장암", variants: ["신장암", "콩팥암", "신세포암", "renal cancer", "kidney cancer", "신세포암종"], type: "disease", tags: ["cancer"] },
  { canonical: "방광암", variants: ["방광암", "bladder cancer", "방광 종양", "방광 악성종양", "요로상피암"], type: "disease", tags: ["cancer"] },
  { canonical: "녹내장", variants: ["녹내장", "glaucoma", "안압 상승", "시신경 손상"], type: "disease", tags: ["chronic_irreversible"] },
  { canonical: "결막염", variants: ["결막염", "눈병", "유행성 결막염", "알레르기성 결막염", "conjunctivitis", "핑크아이", "눈 충혈"], type: "disease" },
  { canonical: "안구건조증", variants: ["안구건조증", "안구 건조", "눈 건조", "눈마름", "건성안", "dry eye"], type: "disease" },
  { canonical: "비문증", variants: ["비문증", "날파리증", "눈 앞 날파리", "눈 떠다니는", "floaters"], type: "disease" },
  { canonical: "다래끼", variants: ["다래끼", "맥립종", "눈다래끼", "산립종", "stye", "hordeolum"], type: "disease" },
  { canonical: "노안", variants: ["노안", "노안 증상", "presbyopia", "가까운 글씨", "근거리 시력"], type: "disease", tags: ["chronic_irreversible"] },
  { canonical: "구내염", variants: ["구내염", "입안 염증", "입병", "혓바늘", "아프타성 구내염", "입안 헐", "mouth ulcer", "canker sore"], type: "disease" },
  { canonical: "충치", variants: ["충치", "치아우식", "치아 우식", "이가 썩", "이 썩", "썩은 이", "cavity", "dental caries"], type: "disease" },
  { canonical: "구순포진", variants: ["구순포진", "입술포진", "입술 포진", "입술 물집", "cold sore", "herpes labialis"], type: "disease", tags: ["infectious"] },
  { canonical: "백반증", variants: ["백반증", "백색증반", "vitiligo", "피부 흰반점", "흰 반점"], type: "disease", tags: ["chronic_irreversible"] },
  { canonical: "화상", variants: ["화상", "데임", "데인 상처", "burn", "1도 화상", "2도 화상", "3도 화상", "열상화상"], type: "disease" },
  { canonical: "기미", variants: ["기미", "색소침착", "색소 침착", "melasma", "기미주근깨"], type: "disease" },
  { canonical: "주름", variants: ["주름", "잔주름", "피부 주름", "노화주름", "표정주름", "wrinkle", "팔자주름"], type: "disease" },
  { canonical: "사마귀", variants: ["사마귀", "물사마귀", "전염성 연속종", "wart", "verruca"], type: "disease", tags: ["infectious"] },
  { canonical: "켈로이드", variants: ["켈로이드", "비대흉터", "비후성 반흔", "keloid", "흉터 증식"], type: "disease" },
  { canonical: "땀띠", variants: ["땀띠", "한진", "땀 발진", "땀띠 발진", "miliaria", "heat rash"], type: "disease" },
  { canonical: "수족냉증", variants: ["수족냉증", "손발 차가움", "손발이 차", "수족 냉증", "손발냉증", "말초혈액순환"], type: "disease" },
  { canonical: "월경전증후군", variants: ["월경전증후군", "생리전증후군", "월경 전 증후군", "PMS", "생리전 증상", "월경전 불편"], type: "disease" },
  { canonical: "월경불순", variants: ["월경불순", "생리불순", "생리 불순", "월경 불순", "불규칙한 생리", "무월경"], type: "disease" },
  { canonical: "자궁내막증", variants: ["자궁내막증", "자궁 내막증", "endometriosis", "내막증"], type: "disease" },
  { canonical: "요실금", variants: ["요실금", "소변 지림", "오줌 지림", "요실금증", "소변 새는"], type: "disease" },
  { canonical: "하지정맥류", variants: ["하지정맥류", "정맥류", "다리 핏줄", "종아리 핏줄", "varicose"], type: "disease" },
  { canonical: "냉증", variants: ["냉증", "냉대하", "질 분비물 증가", "냉이 많", "이상 분비물"], type: "disease" },
  { canonical: "철결핍성빈혈", variants: ["철결핍성빈혈", "철결핍성 빈혈", "철분 부족 빈혈", "철결핍 빈혈", "여성 빈혈", "월경 빈혈"], type: "disease" },
  { canonical: "유선염", variants: ["유선염", "유방염", "젖몸살", "수유 유방통", "mastitis"], type: "disease", tags: ["infectious"] },
  { canonical: "입덧", variants: ["입덧", "임신 구토", "임신 메스꺼움", "임신 입덧", "morning sickness"], type: "disease" },
  { canonical: "산후우울증", variants: ["산후우울증", "산후 우울", "출산 후 우울", "산후 우울감", "postpartum"], type: "disease" },
  { canonical: "유방통", variants: ["유방통", "가슴 통증", "유방 통증", "젖가슴 통증", "유방 멍울"], type: "disease" },
  { canonical: "부종", variants: ["부종", "붓기", "다리 붓", "얼굴 붓", "몸이 붓"], type: "disease" },
  { canonical: "냉방병", variants: ["냉방병", "에어컨병", "여름 감기"], type: "disease" },
  // ── 질환/기능 (건기식·만성질환 타깃) ──
  { canonical: '간건강', variants: ['간 건강', '간건강', '지방간', '간기능', '간 기능', '간수치', '알코올성 간', '숙취'], type: 'disease' },
  { canonical: '간염', variants: ['간염', 'a형간염', 'b형간염', 'c형간염', 'e형간염', 'a형 간염', 'b형 간염', 'c형 간염', 'e형 간염', '바이러스간염', '바이러스성 간염', '황달'], type: 'disease', tags: ['infectious'] },
  { canonical: '암', variants: ['대장암', '위암', '간암', '유방암', '췌장암', '전립선암', '종양', '암 예방', '항암'], type: 'disease', tags: ['cancer'] },
  { canonical: '치매', variants: ['알츠하이머', '치매 예방', '인지기능 저하', '기억력 감퇴'], type: 'disease', tags: ['chronic_irreversible'] },
  { canonical: '인지기능', variants: ['기억력', '집중력', '두뇌건강', '두뇌 건강', '인지력', '학습능력'], type: 'disease' },
  { canonical: '심혈관질환', variants: ['심근경색', '동맥경화', '심장병', '심혈관', '뇌졸중', '중풍', '혈관 건강', '혈행', '혈행 개선', '협심증'], type: 'disease' },
  { canonical: '갑상선', variants: ['갑상선결절', '갑상선 결절', '갑상샘', '갑상선기능', '갑상선 기능'], type: 'disease' },
  { canonical: '관절건강', variants: ['관절', '연골', '관절염', '무릎 관절', '퇴행성관절염', '퇴행성 관절염', '뼈마디'], type: 'disease' },
  { canonical: '체지방', variants: ['복부지방', '복부 지방', '내장지방', '뱃살', '체지방 감소', '체지방감소'], type: 'disease' },
  { canonical: '감기', variants: ['감기', '상기도감염', '코감기', '잔기침'], type: 'disease', tags: ['infectious'] },
  { canonical: '전립선건강', variants: ['전립선', '전립샘', '전립선 건강'], type: 'disease' },
  { canonical: '피부건강', variants: ['피부 건강', '피부건강', '피부 보습', '주름', '피부 탄력'], type: 'disease' },
  { canonical: '갱년기', variants: ['갱년기', '폐경', '갱년기 증상'], type: 'disease' },
  { canonical: '홍역', variants: ['홍역', 'measles'], type: 'disease', tags: ['infectious'] },
  { canonical: '폐렴', variants: ['폐렴', 'pneumonia', '폐렴구균'], type: 'disease', tags: ['infectious'] },
  { canonical: '피로', variants: ['피로 개선', '피로회복', '만성피로', '활력'], type: 'disease' },

  // ── 정보질문 커버리지: 흔히 묻는 감염병/질환 (오타 변형 포함) ──
  { canonical: '뎅기열', variants: ['댕기열', '뎅기', 'dengue', '뎅기열병', '뎅기 바이러스'], type: 'disease', tags: ['infectious'] },
  { canonical: '말라리아', variants: ['malaria', '학질'], type: 'disease', tags: ['infectious'] },
  { canonical: '결핵', variants: ['폐결핵', 'tb', 'tuberculosis'], type: 'disease', tags: ['infectious'] },
  { canonical: '수족구병', variants: ['수족구', '수족구 병', 'hfmd'], type: 'disease', tags: ['infectious'] },
  { canonical: '노로바이러스감염증', variants: ['노로바이러스', '노로', 'norovirus'], type: 'disease', tags: ['infectious'] },
  { canonical: '식중독', variants: ['식중독', '장염', '급성장염', '세균성 장염', '장관감염'], type: 'disease', tags: ['infectious'] },
  { canonical: '백일해', variants: ['백일해', 'pertussis'], type: 'disease', tags: ['infectious'] },
  { canonical: '성홍열', variants: ['성홍열', 'scarlet fever'], type: 'disease', tags: ['infectious'] },
  { canonical: '엠폭스', variants: ['엠폭스', '원숭이두창', 'mpox', 'monkeypox'], type: 'disease', tags: ['infectious'] },
  { canonical: '지카바이러스감염증', variants: ['지카', '지카바이러스', 'zika'], type: 'disease', tags: ['infectious'] },
  { canonical: '수두', variants: ['수두', 'chickenpox', 'varicella'], type: 'disease', tags: ['infectious'] },
  { canonical: '유행성이하선염', variants: ['볼거리', '이하선염', 'mumps'], type: 'disease', tags: ['infectious'] },
  { canonical: '장티푸스', variants: ['장티푸스', 'typhoid'], type: 'disease', tags: ['infectious'] },
  { canonical: '쯔쯔가무시증', variants: ['쯔쯔가무시', '쓰쓰가무시', 'scrub typhus'], type: 'disease', tags: ['infectious'] },

  // ── 정보질문·검증 커버리지: 흔히 묻는 비감염 질환(인식만으로 식약처/완치 룰 발동 → 보류 감소) ──
  { canonical: '위염', variants: ['위장병', '위궤양', '속쓰림', '위산과다', '위장질환', '소화불량', '위장장애'], type: 'disease' },
  { canonical: '역류성식도염', variants: ['역류성 식도염', '위식도역류', '식도염'], type: 'disease' },
  { canonical: '변비', variants: ['변비', '쾌변', '배변장애'], type: 'disease' },
  { canonical: '빈혈', variants: ['빈혈', '철결핍', '철분부족'], type: 'disease' },
  { canonical: '천식', variants: ['천식', '기관지천식', '쌕쌕'], type: 'disease' },
  { canonical: '아토피피부염', variants: ['아토피', '습진', '피부염'], type: 'disease' },
  { canonical: '알레르기비염', variants: ['비염', '알레르기 비염', '코막힘', '콧물 알레르기'], type: 'disease' },
  { canonical: '불면증', variants: ['불면', '불면증', '수면장애', '수면 장애'], type: 'disease' },
  { canonical: '편두통', variants: ['두통', '편두통', '긴장성두통'], type: 'disease' },
  { canonical: '통풍', variants: ['통풍', '요산', '고요산혈증'], type: 'disease', tags: ['chronic_irreversible'] },
  { canonical: '탈모', variants: ['탈모', '모발건강', '머리카락'], type: 'disease' },
  { canonical: '치주질환', variants: ['치주염', '잇몸병', '풍치', '잇몸질환', '치은염'], type: 'disease' },
  { canonical: '방광염', variants: ['방광염', '요로감염', '요로감염증', '오줌소태'], type: 'disease', tags: ['infectious'] },
  { canonical: '백내장', variants: ['백내장', '녹내장'], type: 'disease' },
  { canonical: '우울증', variants: ['우울증', '우울감', '불안장애', '불안증'], type: 'disease' },
  { canonical: '치질', variants: ['치질', '치핵', '항문질환'], type: 'disease' },
  { canonical: '담석', variants: ['담석', '담석증', '쓸개돌'], type: 'disease' },
  // ── 코퍼스 보유 질환(국가건강정보포털 콘텐츠) + 흔한 피부/기타 ──
  { canonical: '건선', variants: ['건선', 'psoriasis'], type: 'disease', tags: ['chronic_irreversible'] },
  { canonical: '객혈', variants: ['객혈', '피를 토', '가래에 피'], type: 'disease' },
  { canonical: '골절', variants: ['골절', '뼈가 부러', '뼈 부러'], type: 'disease' },
  { canonical: '구취', variants: ['구취', '입냄새', '입 냄새'], type: 'disease' },
  { canonical: '기흉', variants: ['기흉', '폐가 쪼그라'], type: 'disease' },
  { canonical: '낙상', variants: ['낙상', '넘어짐', '미끄러져'], type: 'disease' },
  { canonical: '여드름', variants: ['여드름', '뾰루지', 'acne'], type: 'disease' },
  { canonical: '무좀', variants: ['무좀', '발톱무좀', '족부백선'], type: 'disease', tags: ['infectious'] },
  { canonical: '두드러기', variants: ['두드러기', '담마진'], type: 'disease' },
  { canonical: '습진', variants: ['습진', '피부염', '접촉성피부염'], type: 'disease' },
  { canonical: '관절염', variants: ['관절염', '류마티스', '류마티스관절염', '퇴행성관절염'], type: 'disease' },

  // ── 주체: 건강기능식품 성분 (supplement) — '식품' 취급 → 식약처 룰 발동 ──
  { canonical: '오메가3', variants: ['오메가쓰리', 'omega3', 'omega-3', '어유', '오메가삼', 'epa', 'dha', '오메가3지방산'], type: 'subject', tags: ['supplement'] },
  { canonical: '글루코사민', variants: ['glucosamine', '글루코사민황산염'], type: 'subject', tags: ['supplement'] },
  { canonical: '가르시니아', variants: ['가르시니아캄보지아', 'garcinia', 'hca', '가르시니아 캄보지아'], type: 'subject', tags: ['supplement'] },
  { canonical: '밀크씨슬', variants: ['실리마린', 'milk thistle', '카르두스마리아누스', '밀크시슬', '실리빈'], type: 'subject', tags: ['supplement'] },
  { canonical: '코엔자임Q10', variants: ['코큐텐', 'coq10', '코엔자임큐텐', '코엔자임 큐텐', 'q10'], type: 'subject', tags: ['supplement'] },
  { canonical: '은행잎추출물', variants: ['은행잎', '은행잎 추출물', '징코', 'ginkgo', '은행'], type: 'subject', tags: ['supplement'] },
  { canonical: '크릴오일', variants: ['크릴 오일', 'krill', '크릴'], type: 'subject', tags: ['supplement'] },
  { canonical: '홍국', variants: ['홍국쌀', '모나콜린', '홍국 분말', '레드이스트라이스'], type: 'subject', tags: ['supplement'] },
  { canonical: '비타민C', variants: ['비타민씨', 'vitamin c', 'vitc', '아스코르브산', '비타민 c'], type: 'subject', tags: ['supplement'] },
  { canonical: '마그네슘', variants: ['magnesium'], type: 'subject', tags: ['supplement'] },
  { canonical: '아연', variants: ['zinc'], type: 'subject', tags: ['supplement'] },
  { canonical: '쏘팔메토', variants: ['saw palmetto', '쏘팔메토열매추출물', '소팔메토'], type: 'subject', tags: ['supplement'] },
  { canonical: '콜라겐', variants: ['collagen', '저분자콜라겐', '콜라겐펩타이드'], type: 'subject', tags: ['supplement'] },
  { canonical: '크랜베리', variants: ['cranberry', '크랜베리추출물'], type: 'subject', tags: ['supplement'] },
  { canonical: 'msm', variants: ['엠에스엠', '식이유황', 'methylsulfonylmethane'], type: 'subject', tags: ['supplement'] },
  { canonical: '보스웰리아', variants: ['boswellia', '유향'], type: 'subject', tags: ['supplement'] },
  { canonical: '프로폴리스', variants: ['propolis', '프로폴리스추출물'], type: 'subject', tags: ['supplement'] },
  { canonical: '헛개', variants: ['헛개나무', '헛개추출물', '헛개나무열매', '지구자'], type: 'subject', tags: ['supplement', 'folk'] },
  { canonical: '엽산', variants: ['folic acid', '엽산제'], type: 'subject', tags: ['supplement'] },
  { canonical: '철분', variants: ['iron', '철분제'], type: 'subject', tags: ['supplement'] },

  // ── 주체: 일반식품/민간요법 (food/folk) — 식약처 룰 발동(질병 치료·예방 표방 불가) ──
  { canonical: '계피', variants: ['시나몬', 'cinnamon', '계피가루', '계핏가루'], type: 'subject', tags: ['food', 'folk'] },
  { canonical: '양파', variants: ['양파껍질', '양파 껍질', 'onion', '양파즙'], type: 'subject', tags: ['food', 'folk'] },
  { canonical: '마늘', variants: ['흑마늘', 'garlic', '생마늘', '마늘즙'], type: 'subject', tags: ['food', 'folk'] },
  { canonical: '바나바잎', variants: ['바나바', 'banaba', '바나바잎추출물'], type: 'subject', tags: ['folk'] },
  { canonical: '강황', variants: ['커큐민', 'turmeric', 'curcumin', '울금'], type: 'subject', tags: ['food', 'folk'] },
  { canonical: '생강', variants: ['ginger', '생강차'], type: 'subject', tags: ['food', 'folk'] },
  { canonical: '도라지', variants: ['길경', '도라지즙', '도라지청'], type: 'subject', tags: ['food', 'folk'] },
  { canonical: '노니', variants: ['noni', '노니주스'], type: 'subject', tags: ['folk'] },

  // ── 위험요인 음식·행동(조언 질문·위험요인 판정용) ──
  { canonical: '튀긴음식', variants: ['튀긴 음식', '튀김', '기름진음식', '기름진 음식', '기름진', '부침개', '치킨', '고지방식', '고지방 음식', '지방많은 음식', '지방 많은 음식'], type: 'subject', tags: ['food', 'nutrient'] },
  { canonical: '포화지방', variants: ['동물성지방', '동물성 지방', '삼겹살', '버터', '비계', '라드'], type: 'subject', tags: ['food', 'nutrient'] },
  { canonical: '트랜스지방', variants: ['마가린', '쇼트닝', '경화유'], type: 'subject', tags: ['food', 'nutrient'] },
  { canonical: '가공식품', variants: ['인스턴트', '라면', '가공육', '햄', '소시지', '패스트푸드', '인스턴트 식품'], type: 'subject', tags: ['food'] },
  { canonical: '음주', variants: ['술', '알코올', '과음', '맥주', '소주', '음주습관'], type: 'subject', tags: ['behavior', 'food'] },
  { canonical: '야식', variants: ['밤참', '야식습관', '늦은 밤 음식'], type: 'subject', tags: ['behavior', 'food'] },
  { canonical: '과식', variants: ['폭식', '과식습관'], type: 'subject', tags: ['behavior'] },
  { canonical: '흡연', variants: ['담배', '담배를 피', '담배 피', '흡연습관', '골초', '담배를 오래'], type: 'subject', tags: ['behavior'] },
  { canonical: '카페인', variants: ['커피', '에너지음료', '카페인 음료'], type: 'subject', tags: ['food'] },
  { canonical: '아이스크림', variants: ['빙과', '찬 음식', '차가운 음식', '찬 음료'], type: 'subject', tags: ['food'] },
  { canonical: '좌식생활', variants: ['운동부족', '운동 부족', '앉아만', '활동부족'], type: 'subject', tags: ['behavior'] },
]
